INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Grande piscine extérieure avec transats', 'Piscine extérieure');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Piscine intérieure chauffée accessible toute l''année', 'Piscine intérieure');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Salle de sport équipée de machines modernes', 'Salle de sport');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Espace détente avec jacuzzi et sauna', 'Spa');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Salle équipée pour les conférences et les séminaires', 'Salle de conférence');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Parking souterrain sécurisé pour les clients', 'Parking souterrain');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Terrain de tennis en plein air', 'Terrain de tennis');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Espace de jeux pour enfants avec diverses activités', 'Aire de jeux');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Restaurant gastronomique avec menu international', 'Restaurant');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Bar lounge avec ambiance musicale', 'Bar');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Centre de bien-être offrant des massages et des soins', 'Centre de bien-être');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Service de blanchisserie et de nettoyage à sec', 'Blanchisserie');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Bibliothèque avec une large sélection de livres', 'Bibliothèque');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Salle de cinéma privée pour les clients', 'Salle de cinéma');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Salon de coiffure et de beauté', 'Salon de coiffure');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Salle de jeux avec billard et jeux vidéo', 'Salle de jeux');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Jardin privé avec espace de détente', 'Jardin');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Service de navette vers l''aéroport', 'Navette aéroport');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Boutique de souvenirs et de cadeaux', 'Boutique');
INSERT INTO equipement (description_equipement, nom_equipement) VALUES ('Terrasse panoramique avec vue sur la ville', 'Terrasse panoramique');