INSERT INTO option (nom_option) VALUES ('Petit-déjeuner buffet');
INSERT INTO option (nom_option) VALUES ('Massage relaxant');
INSERT INTO option (nom_option) VALUES ('Accès au spa');
INSERT INTO option (nom_option) VALUES ('WiFi rapide');
INSERT INTO option (nom_option) VALUES ('Dîner gastronomique');
INSERT INTO option (nom_option) VALUES ('Transfert aéroport');
INSERT INTO option (nom_option) VALUES ('Service de blanchisserie');
INSERT INTO option (nom_option) VALUES ('Minibar');
INSERT INTO option (nom_option) VALUES ('Service en chambre');
INSERT INTO option (nom_option) VALUES ('Parking sécurisé');
INSERT INTO option (nom_option) VALUES ('Location de vélo');
INSERT INTO option (nom_option) VALUES ('Excursion guidée');
INSERT INTO option (nom_option) VALUES ('Cours de cuisine');
INSERT INTO option (nom_option) VALUES ('Boissons à volonté');
INSERT INTO option (nom_option) VALUES ('Coffre-fort');
INSERT INTO option (nom_option) VALUES ('Accès à la salle de sport');
INSERT INTO option (nom_option) VALUES ('Petit-déjeuner en chambre');
INSERT INTO option (nom_option) VALUES ('Kit de bienvenue');
INSERT INTO option (nom_option) VALUES ('Service de réveil');
INSERT INTO option (nom_option) VALUES ('Visite de la ville');